### ISSUE TITLE
Click Animation Is Sped up in Game

### ISSUE THREAD

**Issue by ghost** [ate47/cursormod#12]
The click animation plays normally in the main menu and options menu, but is choppy and sped up while the player is loaded into a world. The effect is subtle but noticeable.

Main menu and options menu:
![](https://i.imgur.com/XdWKUiY.gif)

All menus while loaded into a world (including the options menu):
![](https://i.imgur.com/EHZGwFm.gif)

- Minecraft version:   **1.18.2**
- Fabric loader version:   **0.14.8**
- Fabric API version:   **0.56.1**
- Custom cursor mod version:   **1.3.1**

I am using custom textures for the cursor and click animation that I made myself, but this should not affect anything.

**Comment by ate47** [comment]
I’m not at home so I write this here for future myself:

				cursorClick.descreaseTime();
