### ISSUE TITLE
Crash on forge 1.19.2 startup.

### ISSUE THREAD

**Issue by murao-kun** [ate47/cursormod#15]
### Mod version

1.3.2

### Minecraft version

1.19.2

### Mod loader

Forge

### Description of the issue

Crashing on start up.

### Excepted behavior

To do not crush.

### Something else?

[crash-2022-08-15_18.41.12-fml.txt](https://github.com/ate47/CursorMod/files/9338282/crash-2022-08-15_18.41.12-fml.txt)

**Comment by Taknax** [comment]
Same issue here.

**Comment by TheeMrCheeky** [comment]
same 
![image](https://user-images.githubusercontent.com/96976998/189163055-ae367480-a968-4fe9-9049-44fb971db4d4.png)

**Comment by ghost** [comment]
2 Months later same issue. 10/10 mod

**Comment by TheeMrCheeky** [comment]
I know some mod makers where waiting on forge to do stuff since forge was down for a few months.. But forge started putting out updates again... Be nice to see this mod fixed?.. Really good mod I use in all my packs :,D

**Comment by ate47** [comment]
> 2 Months later same issue. 10/10 mod

Or you can do it yourself instead of whining in the repository of someone who hasn't played Minecraft for years, no?

**Comment by ate47** [comment]
fixed, should be available here after processing: https://www.curseforge.com/minecraft/mc-mods/cursor-mod/files/4119949
