### ISSUE TITLE
Cursors are disappearing in 1.7.10

### ISSUE THREAD

**Issue by silent-mobious** [ate47/CursorMod#2]
It looks like using CustomCursorMod1.2-1.7.10.jar and changing the focus from the Minecraft window and then back makes the cursors disappear in the menu screens.   Without restarting they don't return, however you can still move the mouse and the location where the cursor 'is' still functions properly.   Any ideas?  Optifine causing an issue?  Doesn't appear to be anything relevant to it in the logs when it occurs.  Thanks!

Relevant info:
Forge Mod Loader version 7.99.40.1614
OptiFine_1.7.10_HD_U_E3

**Comment by silent-mobious** [comment]
Looks like the new version works.  I was able to switch focus from the Minecraft window and back again and the cursors remained visible.  Thanks for the quick fix, looks really good!

**Comment by Dalethium** [comment]
Hey so this issue is still happening in 1.12.2 -- it only happens after a while in game - i can't find the trigger. The click animation stays though.

**Comment by TheVisionaryOne** [comment]
^ This issue is _still_ happening. It's really annoying. Almost makes the game unplayable when using this mod.
