### ISSUE TITLE
Cursor Texture Error

### ISSUE THREAD

**Issue by CCCClear** [ate47/cursormod#21]
### The bug occurs without having Optifine or Optifabric installed? (Optifine bugs won't be fixed)

- [X] Yes, I don't have Optifine install.

### Mod version

1.3.0

### Minecraft version

1.18

### Mod loader

Forge

### Description of the issue

Red and blue channels of texture are swapped around after an import.

### Excepted behavior

There is no problem with the preset texture because it is completely grey. Although I was able to adjust the channels of the image directly, it was cumbersome and I had to swap channels after each coloring.

### Do I want to contribute to fix it?

None

**Comment by ate47** [comment]
True, I'm on it

![image](https://user-images.githubusercontent.com/1580223/205490331-a0b676be-57ed-475f-b4d6-35c16bfb053f.png)
